baseURL = 'https://formula1an.com/'
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
enableEmoji = true
title = 'FORMULA1AN'
copyright = 'Formula1AN'
theme = 'hugo-theme-itheme'
paginate = 10
[params]
  [params.logo]
    path = "logo.png"
    alt = "FORMULA1AN"
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://twitter.com/formula1an'
  [[params.socialMedia]]
    name = 'Instagram'
    url = 'https://instagram.com/formula1an'

